<a href="https://colab.research.google.com/github/websitecreatr99/Time_Complexity_and_Feature_Importance/blob/main/Time_complexity_and_feature_importance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

In [ ]:
# pred_probas = np.random.rand(100000)
# y_true = np.random.randint(0,2,100000)
X,y = make_classification(n_samples=200000, n_features=5, n_informative=2)

In [ ]:
#  df = pd.DataFrame({'pred_proba': pred_probas, 'target': y_true})
#  df=df.rename(columns={'pred':'pred_proba', 'label':'target' })
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'feature3':X[:,2],'feature4':X[:,3],'feature5':X[:,4],'target':y})
# df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [ ]:
df

feature1  feature2  feature3  feature4  feature5  target
0       1.724699  0.885771  1.027234  0.382191 -1.354357       1
1       0.690699  0.808820 -0.054897 -1.277673 -0.254895       0
2      -0.124213  0.771015 -0.931196  0.148692  0.626071       0
3       1.897433  0.208592  1.916562 -0.052849 -1.974897       1
4      -3.203635 -1.578378 -1.976833  0.225603  2.558107       0
...          ...       ...       ...       ...       ...     ...
199995 -2.862425 -1.613792 -1.557302 -0.415272  2.156797       0
199996 -1.714335 -1.987075  0.115268  0.190929  0.645595       1
199997  1.940321  0.896137  1.258727 -0.101050 -1.587227       1
199998 -3.539523 -1.820889 -2.105005 -0.364281  2.777549       0
199999 -1.487575 -1.038477 -0.604148  0.211183  0.994368       0

[200000 rows x 6 columns]

In [ ]:
df.shape

(200000, 6)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.5,random_state=3)

In [ ]:
X_train.shape

(100000, 5)

In [ ]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 MB 9.6 MB/s eta 0:00:00


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from catboost import CatBoostClassifier

In [ ]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train,y_train)
y_pred_dt = model_dt.predict(X_test)

In [ ]:
model_rfc = DecisionTreeClassifier()
model_rfc.fit(X_train,y_train)
y_pred_rfc = model_rfc.predict(X_test)

In [ ]:
model_cbr = CatBoostClassifier()
model_cbr.fit(X_train, y_train)
y_preds_cbr = model_cbr.predict(X_test)

Learning rate set to 0.07361
0:	learn: 0.5840721	total: 21.7ms	remaining: 21.7s
1:	learn: 0.4959224	total: 43.8ms	remaining: 21.8s
2:	learn: 0.4268792	total: 66.8ms	remaining: 22.2s
3:	learn: 0.3732563	total: 88.1ms	remaining: 21.9s
4:	learn: 0.3334901	total: 110ms	remaining: 21.8s
5:	learn: 0.3013384	total: 130ms	remaining: 21.6s
6:	learn: 0.2736444	total: 151ms	remaining: 21.4s
7:	learn: 0.2544743	total: 173ms	remaining: 21.5s
8:	learn: 0.2380663	total: 199ms	remaining: 21.9s
9:	learn: 0.2233999	total: 222ms	remaining: 21.9s
10:	learn: 0.2112258	total: 245ms	remaining: 22s
11:	learn: 0.2010674	total: 271ms	remaining: 22.3s
12:	learn: 0.1927527	total: 294ms	remaining: 22.3s
13:	learn: 0.1854736	total: 317ms	remaining: 22.4s
14:	learn: 0.1786761	total: 339ms	remaining: 22.2s
15:	learn: 0.1732085	total: 360ms	remaining: 22.2s
16:	learn: 0.1684275	total: 383ms	remaining: 22.1s
17:	learn: 0.1635971	total: 408ms	remaining: 22.3s
18:	learn: 0.1599444	total: 429ms	remaining: 22.2s
19:	learn:

## Time Complexity

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
import time

start_time = time.time()
print("Accuracy",accuracy_score(y_test,y_pred_dt))
end_time = time.time()
print("Time Taken",end_time - start_time)


Accuracy 0.95494
Time Taken 0.016747713088989258


In [ ]:
start_time = time.time()
print("Accuracy",accuracy_score(y_test,y_pred_dt))
end_time = time.time()
print("Time Taken",end_time - start_time)


Accuracy 0.95494
Time Taken 0.017385244369506836


In [ ]:
start_time = time.time()
print("Accuracy",accuracy_score(y_test,y_pred_dt))
end_time = time.time()
print("Time Taken",end_time - start_time)


Accuracy 0.95494
Time Taken 0.017493486404418945


## Feature Importance

In [ ]:
importances = model_dt.feature_importances_
sorted_indices = np.argsort(importances)[::-1]

print(importances)
print(sorted_indices)

# feat_labels = df.columns[1:]
 
# for f in range(X_train.shape[1]):
#     print("%2d) %-*s %f" % (f + 1, 30,
#                             feat_labels[sorted_indices[f]],
#                             importances[sorted_indices[f]]))

[0.09045174 0.19459653 0.62698713 0.02183444 0.06613016]
[2 1 0 4 3]


In [ ]:
importances = model_rfc.feature_importances_
sorted_indices = np.argsort(importances)[::-1]

print(importances)
print(sorted_indices)

[0.09108319 0.19402568 0.62751038 0.02210953 0.06527122]
[2 1 0 4 3]


In [ ]:
importances = model_cbr.feature_importances_
sorted_indices = np.argsort(importances)[::-1]

print(importances)
print(sorted_indices)

[25.12017721 35.07763739 28.8261299   4.15653161  6.81952388]
[1 2 0 4 3]
